<?php

// DO NOT EDIT THIS FILE

/**
 * The values used in this class will be changed when we grade your solution.
 * Hence, no hardcoding in your solution!
 */

    function getClubNames() {
        return [ "Ellipsis", "IndanCity", "Soccer"];
    }

    function getMembersBreakdown($club_name) {
        if ( $club_name === "Ellipsis" ) {
            return [
                "SIS" => [
                    2015 => [
                        "Chinese" => 2,
                        "Malay" => 2,
                    ],
                    2016 => [
                        "Malay" => 1,
                        "Chinese" => 2,
                        "Indian" => 1,
                    ],
                    2017 => [
                        "Korean" => 3,
                    ],
                ]
            ];
        }
        if ( $club_name === "IndanCity" ) {
            return [
                "SIS" => [
                    2016 => [
                        "Indian" => 2,
                    ],
                    2017 => [
                        "Chinese" => 1,
                        "Korean" => 1,
                    ],
                ],
                "SOA" => [
                    2015 => [
                        "Malay" => 1,
                    ],
                    2017 => [
                        "Korean" => 1,
                    ],
                ],
                "SOSS" => [
                    2016 => [
                        "Japan" => 3,
                    ],
                ]                
            ];
        }
        if ( $club_name === "Soccer" ) {
            return [
                "SOA" => [
                    2017 => [
                        "Malay" => 5,
                        "Indian" => 4,
                    ],
                    2016 => [
                        "Chinese" => 2,
                    ],
                ],
                "SOSS" => [
                    2017 => [
                        "Korean" => 1,
                    ],
                ]                
            ];
        }
        return [];
    }
